# Path B — Hybrid Market-Aware Scoring Configuration
# Ability-only training + market-aware scoring for increased volume

model:
  name: "hrd_win_prob_ability"
  stage: "Production"  # or specific version

snapshot:
  minutes_before: 60  # T-60 snapshot
  source: "win_ppwap"  # Betfair Pre-Play WAP

market:
  commission: 0.02  # 2% Betfair commission
  
odds_caps:
  min: 7.0  # Slightly wider range (was 8.0)
  max: 16.0  # Slightly wider (was 15.0)

liquidity:
  min_gbp: 250  # Minimum £250 available at best back

# Odds-band specific lambda (blending factor)
# p_blend = (1 - λ) * p_model + λ * q_vigfree
# Higher λ = trust market more
lambda_by_odds:
  "1.5-3.0": 0.70    # Favorites: trust market MORE (was 0.60)
  "3.0-5.0": 0.60    # Short prices: trust market MORE (was 0.45)
  "5.0-8.0": 0.40    # Mid prices: increased trust (was 0.30)
  "8.0-12.0": 0.15   # Proven sweet spot: keep same
  "12.0-999": 0.50   # Longshots: more hedging (was 0.35)

# Banded edge minimums (percentage points)
# DRAMATICALLY INCREASED to reduce volume
edge_min_by_odds:
  "1.5-3.0": 0.20    # 20pp - much stricter
  "3.0-5.0": 0.15    # 15pp - much stricter
  "5.0-8.0": 0.15    # 15pp - slightly tighter (was 14pp)
  "8.0-12.0": 0.15   # 15pp - slightly tighter (was 14pp)
  "12.0-999": 0.16   # 16pp - moderate

# Minimum EV requirements by band
ev_min_by_odds:
  "1.5-3.0": 0.02    # 2% minimum
  "3.0-5.0": 0.02    # 2% minimum
  "5.0-8.0": 0.02    # 2% minimum
  "8.0-12.0": 0.02   # 2% minimum
  "12.0-999": 0.03   # 3% for longshots

# Kelly staking
kelly:
  fraction: 0.25  # Quarter Kelly (conservative)
  cap_units: 0.5  # Maximum 0.5 units per bet
  
# Additional favorite penalty
favorite_caps:
  odds_threshold: 3.0  # Apply to odds < 3.0
  max_stake_units: 0.25  # Cap at 0.25 units

# Selection gates
selection:
  top_n_per_race: 1  # Only top-1 selection per race
  max_bets_per_day: 20  # Daily volume cap
  
# Risk controls
risk:
  max_stake_per_race: 1.0  # Units
  max_stake_per_day: 10.0  # Units
  stop_loss_per_day: 6.0   # Stop if down 6 units

# Optional filters
filters:
  exclude_maidens: false  # Set true if maiden races too noisy
  min_field_size: 4
  max_field_size: 20

# Targets (for monitoring)
targets:
  min_bets_per_year: 200
  max_bets_per_year: 500
  min_roi: 0.05  # 5% after commission
  target_roi: 0.10  # 10% target
  min_clv: 0.0  # Closing line value vs market

# Backtest dates
backtest:
  train_from: "2006-01-01"
  train_to: "2023-12-31"
  test_from: "2024-01-01"
  test_to: "2025-10-16"

