# Path B — Hybrid Market-Aware Scoring Configuration
# Ability-only training + market-aware scoring for increased volume

model:
  name: "hrd_win_prob_ability"
  stage: "Production"  # or specific version

snapshot:
  minutes_before: 60  # T-60 snapshot
  source: "win_ppwap"  # Betfair Pre-Play WAP

market:
  commission: 0.02  # 2% Betfair commission
  
odds_caps:
  min: 2.0  # Avoid very short favorites
  max: 30.0  # Hard cap on longshots

liquidity:
  min_gbp: 250  # Minimum £250 available at best back

# Odds-band specific lambda (blending factor)
# p_blend = (1 - λ) * p_model + λ * q_vigfree
# Higher λ = trust market more
lambda_by_odds:
  "1.5-3.0": 0.60    # Favorites: trust market heavily
  "3.0-5.0": 0.45    # Short prices: moderate trust
  "5.0-8.0": 0.30    # Mid prices: some trust
  "8.0-12.0": 0.15   # Proven sweet spot: trust model more
  "12.0-999": 0.35   # Longshots: hedge with market

# Banded edge minimums (percentage points)
# edge_pp = p_blend - q_vigfree
edge_min_by_odds:
  "1.5-3.0": 0.12    # 12pp - market most efficient
  "3.0-5.0": 0.08    # 8pp - moderate
  "5.0-8.0": 0.06    # 6pp - easier
  "8.0-12.0": 0.04   # 4pp - sweet spot
  "12.0-999": 0.08   # 8pp - guard longshots

# Minimum EV requirements by band
ev_min_by_odds:
  "1.5-3.0": 0.02    # 2% minimum
  "3.0-5.0": 0.02    # 2% minimum
  "5.0-8.0": 0.02    # 2% minimum
  "8.0-12.0": 0.02   # 2% minimum
  "12.0-999": 0.03   # 3% for longshots

# Kelly staking
kelly:
  fraction: 0.25  # Quarter Kelly (conservative)
  cap_units: 0.5  # Maximum 0.5 units per bet
  
# Additional favorite penalty
favorite_caps:
  odds_threshold: 3.0  # Apply to odds < 3.0
  max_stake_units: 0.25  # Cap at 0.25 units

# Selection gates
selection:
  top_n_per_race: 1  # Only top-1 selection per race
  max_bets_per_day: 20  # Daily volume cap
  
# Risk controls
risk:
  max_stake_per_race: 1.0  # Units
  max_stake_per_day: 10.0  # Units
  stop_loss_per_day: 6.0   # Stop if down 6 units

# Optional filters
filters:
  exclude_maidens: false  # Set true if maiden races too noisy
  min_field_size: 4
  max_field_size: 20

# Targets (for monitoring)
targets:
  min_bets_per_year: 200
  max_bets_per_year: 500
  min_roi: 0.05  # 5% after commission
  target_roi: 0.10  # 10% target
  min_clv: 0.0  # Closing line value vs market

# Backtest dates
backtest:
  train_from: "2006-01-01"
  train_to: "2023-12-31"
  test_from: "2024-01-01"
  test_to: "2025-10-16"

